export const data = {
  bentuk_koperasi: [
    "~",
    "Primer Kota",
    "Primer Provinsi",
    "Primer Nasional",
    "Sekunder Kota",
    "Sekunder Provinsi",
    "Sekunder Nasional",
  ],
  jenis_koperasi: [
    "~",
    "Konsumen",
    "Produsen",
    "Jasa",
    "Pemasaran",
    "Simpan Pinjam",
  ],
  kelompok_koperasi: [
    "~",
    "KUD",
    "Koperasi Pertanian",
    "Koperasi Perkebunan",
    "Koperasi Peternakan",
    "Koperasi Nelayan",
    "Koperasi Kehutanan",
    "KOPTI",
    "KOPRA",
    "KOPINKRA",
    "KOPPONTREN",
    "KOPKAR",
    "Koperasi Angkatan Darat",
    "Koperasi Angkatan Laut",
    "Koperasi Angkatan Udara",
    "Koperasi Kepolisian",
    "Koperasi Serba Usaha",
    "Koperasi Pasar",
    "Koperasi Simpan Pinjam",
    "Operasi Angkutan Darat",
    "Koperasi Angkutan Laut",
    "Koperasi Angkutan Udara",
    "Koperasi Angkutan Sungai",
    "Koperasi Angkutan Penyeberangan",
    "Koperasi Wisata",
    "Operasi Telkom",
    "Koperasi Perumahan",
    "K.B.P.R.",
    "Koperasi Pegawai Negeri (KPRI)",
    "Koperasi Listrik Pedesaan",
    "Koperasi Listrik Pedesaan",
    "Koperasi Asuransi Indonesia",
    "Koperasi Wanita",
    "Koperasi Profesi",
    "Koperasi Veteran",
    "Koperasi Pepabri",
    "Koperasi Wredatama",
    "Koperasi Mahasiswa",
    "Koperasi Pemuda",
    "Koperasi Pertambangan",
    "Koperasi Pedagang Kaki Lima",
    "Koperasi Jamu Gendong",
    "Koperasi Lainnya",
    "Koperasi Simpan Pinjam Pola Syariah",
    "Koperasi Sekunder",
  ],
  sektor_usaha: [
    "~",
    "Pertanian, Kehutanan dan Perikanan",
    "Pertambangan dan Penggalian",
    "Industri Pengolahan",
    "Pengadaan Listrik dan Gas",
    "Pengadaan Air, Pengelolaan Sampah, Limbah dan Daur Ulang",
    "Konstruksi",
    "Perdagangan Besar dan Eceran - Reparasi Mobil dan Motor",
    "Transportasi dan Pergudangan",
    "Penyediaan Akomodasi dan Makan Minum",
    "Informasi dan Komunikasi",
    "Jasa Keuangan dan Asuransi",
    "Real Estate",
    "Jasa Perumahan",
    "Adm. Pemerintah Pertahanan dan Jaminan Sosial",
    "Jasa Pendidikan",
    "Jasa Kesehatan dan Kegiatan Sosial",
    "Jasa Lainnya",
  ],
};
